// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCfe1aVOoofP1re1dMK-t2CXFUGAIF91HM',
    appId: '1:556379754584:web:c29c75cc1dd39300403a2d',
    messagingSenderId: '556379754584',
    projectId: 'selorize',
    authDomain: 'selorize.firebaseapp.com',
    storageBucket: 'selorize.firebasestorage.app',
    measurementId: 'G-ZKYDYN4VGP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD43doo1aWUMiywKEoKTCaOFdqr7YyDhhk',
    appId: '1:556379754584:android:604ea27d0fef3faa403a2d',
    messagingSenderId: '556379754584',
    projectId: 'selorize',
    storageBucket: 'selorize.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAFkeydfAAzApE3xrOFSeu_z_La-YvBlmA',
    appId: '1:556379754584:ios:6e2c0bfd0de87f17403a2d',
    messagingSenderId: '556379754584',
    projectId: 'selorize',
    storageBucket: 'selorize.firebasestorage.app',
    androidClientId: '556379754584-palhm7b35ctjn74sbhnv6qj21amfmba8.apps.googleusercontent.com',
    iosClientId: '556379754584-gi3l809joskh9djutcd2mfnvm263h3nj.apps.googleusercontent.com',
    iosBundleId: 'com.selorize.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAFkeydfAAzApE3xrOFSeu_z_La-YvBlmA',
    appId: '1:556379754584:ios:fd46d3b13e49078a403a2d',
    messagingSenderId: '556379754584',
    projectId: 'selorize',
    storageBucket: 'selorize.firebasestorage.app',
    androidClientId: '556379754584-palhm7b35ctjn74sbhnv6qj21amfmba8.apps.googleusercontent.com',
    iosClientId: '556379754584-v3c2vka81e7j172065qesl78o36btjhs.apps.googleusercontent.com',
    iosBundleId: 'com.example.selorize',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCfe1aVOoofP1re1dMK-t2CXFUGAIF91HM',
    appId: '1:556379754584:web:4e5afe3374989e20403a2d',
    messagingSenderId: '556379754584',
    projectId: 'selorize',
    authDomain: 'selorize.firebaseapp.com',
    storageBucket: 'selorize.firebasestorage.app',
    measurementId: 'G-N5CPGML81X',
  );

}